services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - payment-service-data:/var/lib/postgresql/data
    networks:
      - e_com_network

  payment-service:
    build: .
    ports:
      - '${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}'
    environment: DATABASE_URL:${DOCKER_DATABASE_URL}
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - e_com_network

volumes:
  payment-service-data:

networks:
  e_com_network:
    external: true
