services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - user_service_data:/var/lib/postgresql/data
    networks:
      - e_com_network

  user-service:
    build: .
    ports:
      - '${USER_SERVICE_PORT}:${USER_SERVICE_PORT}'
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
      - PORT=${USER_SERVICE_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
    depends_on:
      - postgres
    volumes:
      - ./:/app # Mounts your local project directory => # ./dist:/usr/src/app/ for production
      - /app/node_modules # An empty anonymous volume to "hide" the local node_modules
    networks:
      - e_com_network

volumes:
  user_service_data:

networks:
  e_com_network:
    external: true
